// <auto-generated />
using System;
using FSP.Api.Infrastructure.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FSP.Api.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260702152156_AddJogadorFoto")]
    partial class AddJogadorFoto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FSP.Api.Domain.Entities.JogadorFoto.JogadorFoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID_JOGADOR_FOTO");

                    b.Property<Guid?>("AtualizadoPorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("ID_USUARIO");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_CRIADO_EM");

                    b.Property<string>("CriadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TX_CRIADO_POR");

                    b.Property<DateTimeOffset>("DataModificacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_MODIFICACAO");

                    b.Property<bool>("Excluido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("FL_EXCLUIDO");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TX_MODIFICADO_POR");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("TX_NOME_ARQUIVO");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("TX_PLAYER_ID");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("TX_PLAYER_NAME");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique()
                        .HasDatabaseName("IX_JOGADOR_FOTO_PLAYER_ID");

                    b.ToTable("T_JOGADOR_FOTO", (string)null);
                });

            modelBuilder.Entity("FSP.Api.Domain.Entities.Log.Logs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_LOG");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgenteUsuario")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("TX_AGENTE_USUARIO");

                    b.Property<DateTimeOffset?>("DataHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_DATA_HORA");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("TX_DESCRICAO");

                    b.Property<string>("Detalhes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TX_DETALHES");

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("TX_EMAIL_USUARIO");

                    b.Property<string>("EnderecoIp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("TX_ENDERECO_IP");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("NM_USUARIO");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("TX_URL");

                    b.HasKey("Id");

                    b.HasIndex("DataHora")
                        .HasDatabaseName("IX_LOG_DATA_HORA");

                    b.HasIndex("EmailUsuario")
                        .HasDatabaseName("IX_LOG_EMAIL_USUARIO");

                    b.HasIndex("NomeUsuario")
                        .HasDatabaseName("IX_LOG_NOME_USUARIO");

                    b.ToTable("T_LOG", (string)null);
                });

            modelBuilder.Entity("FSP.Api.Domain.Entities.Palpite.Palpite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID_PALPITE");

                    b.Property<int>("AwayGoals")
                        .HasColumnType("integer")
                        .HasColumnName("QTD_GOLS_FORA");

                    b.Property<string>("AwayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TX_TIME_FORA");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_CRIADO_EM");

                    b.Property<string>("CriadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TX_CRIADO_POR");

                    b.Property<DateTimeOffset>("DataModificacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_MODIFICACAO");

                    b.Property<int>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("ID_EVENTO");

                    b.Property<bool>("Excluido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("FL_EXCLUIDO");

                    b.Property<int>("HomeGoals")
                        .HasColumnType("integer")
                        .HasColumnName("QTD_GOLS_CASA");

                    b.Property<string>("HomeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TX_TIME_CASA");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TX_MODIFICADO_POR");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("TX_APELIDO");

                    b.Property<string>("Stage")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("TX_FASE");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "Nickname")
                        .IsUnique()
                        .HasDatabaseName("IX_PALPITE_EVENTO_APELIDO");

                    b.ToTable("T_PALPITE", (string)null);
                });

            modelBuilder.Entity("FSP.Api.Domain.Entities.Permission.Permissao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID_PERMISSAO");

                    b.Property<string>("Categoria")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CTG_PERMISSAO");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriadoPor")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DataModificacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("DS_PERMISSAO");

                    b.Property<bool>("Excluido")
                        .HasColumnType("boolean");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("NM_PERMISSAO");

                    b.Property<string>("NomeExibicao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("NM_EXIBICAO");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.HasIndex("Excluido");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("T_PERMISSAO", (string)null);
                });

            modelBuilder.Entity("FSP.Api.Domain.Entities.Post.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID_POST");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("AUTOR_ID");

                    b.Property<string>("CapaUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("TX_CAPA_URL");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("TX_CATEGORIA");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TX_CONTEUDO");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_CRIADO_EM");

                    b.Property<string>("CriadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TX_CRIADO_POR");

                    b.Property<DateTimeOffset>("DataModificacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_MODIFICACAO");

                    b.Property<bool>("Excluido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("FL_EXCLUIDO");

                    b.Property<int>("MinutosLeitura")
                        .HasColumnType("integer")
                        .HasColumnName("QTD_MINUTOS_LEITURA");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TX_MODIFICADO_POR");

                    b.Property<DateTimeOffset>("PublicadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_PUBLICADO_EM");

                    b.Property<string>("Resumo")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("character varying(280)")
                        .HasColumnName("TX_RESUMO");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("character varying(350)")
                        .HasColumnName("TX_SLUG");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("TX_TITULO");

                    b.Property<int>("Visualizacoes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("QTD_VISUALIZACOES");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("Categoria")
                        .HasDatabaseName("IX_POST_CATEGORIA");

                    b.HasIndex("Excluido")
                        .HasDatabaseName("IX_POST_EXCLUIDO");

                    b.HasIndex("PublicadoEm")
                        .HasDatabaseName("IX_POST_PUBLICADO_EM");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_POST_SLUG");

                    b.ToTable("T_POST", (string)null);
                });

            modelBuilder.Entity("FSP.Api.Domain.Entities.Usuario.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID_USUARIO");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("QTD_TENTATIVAS_FALHAS");

                    b.Property<string>("CPF")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("TX_CPF");

                    b.Property<bool>("CanPublish")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("FL_CAN_PUBLISH");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("TX_CONCURRENCY_STAMP");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_CRIADO_EM");

                    b.Property<string>("CriadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TX_CRIADO_POR");

                    b.Property<DateTime?>("DataExpiracaoRefreshToken")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("DT_EXPIRACAO_REFRESH_TOKEN");

                    b.Property<DateTimeOffset>("DataModificacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_MODIFICACAO");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("TX_EMAIL");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("FL_EMAIL_CONFIRMADO");

                    b.Property<bool>("Excluido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("FL_EXCLUIDO");

                    b.Property<DateTime?>("ExpiracaoPrimeiroAcesso")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("DT_EXPIRACAO_PRIMEIRO_ACESSO");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("FL_BLOQUEIO_HABILITADO");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_FIM_BLOQUEIO");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TX_MODIFICADO_POR");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("NM_COMPLETO");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("TX_EMAIL_NORMALIZADO");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("NM_USUARIO_NORMALIZADO");

                    b.Property<bool>("NotificacaoEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("FL_NOTIFICACAO_EMAIL");

                    b.Property<bool>("NotificacaoSMS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("FL_NOTIFICACAO_SMS");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("TX_SENHA_HASH");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("NR_TELEFONE_IDENTITY");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("FL_TELEFONE_CONFIRMADO");

                    b.Property<string>("PrimeiroTokenAcesso")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("TX_PRIMEIRO_TOKEN_ACESSO");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("TX_REFRESH_TOKEN");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("TX_SECURITY_STAMP");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("NR_TELEFONE");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("FL_TWO_FACTOR_HABILITADO");

                    b.Property<string>("TxFoto")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("TX_FOTO");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("NM_USUARIO");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_USUARIO_EMAIL");

                    b.HasIndex("Excluido")
                        .HasDatabaseName("IX_USUARIO_EXCLUIDO");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("IX_USUARIO_EMAIL_NORMALIZADO");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("IX_USUARIO_NOME_NORMALIZADO");

                    b.ToTable("T_USUARIO", (string)null);
                });

            modelBuilder.Entity("FSP.Api.Domain.Entities.Usuario.Perfil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID_PERFIL");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("TX_CONCURRENCY_STAMP");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_CRIADO_EM");

                    b.Property<string>("CriadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TX_CRIADO_POR");

                    b.Property<DateTimeOffset>("DataModificacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DT_MODIFICACAO");

                    b.Property<bool>("Excluido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("FL_EXCLUIDO");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TX_MODIFICADO_POR");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("NM_PERFIL");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("NM_PERFIL_NORMALIZADO");

                    b.HasKey("Id");

                    b.HasIndex("Excluido")
                        .HasDatabaseName("IX_PERFIL_EXCLUIDO");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("IX_PERFIL_NOME_NORMALIZADO");

                    b.ToTable("T_PERFIL", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_PERFIL_CLAIM");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("TX_TIPO_CLAIM");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("TX_VALOR_CLAIM");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("ID_PERFIL");

                    b.HasKey("Id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_PERFIL_CLAIM_ID_PERFIL");

                    b.ToTable("T_PERFIL_CLAIM", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_USUARIO_CLAIM");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("TX_TIPO_CLAIM");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("TX_VALOR_CLAIM");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_USUARIO_CLAIM_ID_USUARIO");

                    b.ToTable("T_USUARIO_CLAIM", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("TX_PROVEDOR_LOGIN");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("TX_CHAVE_PROVEDOR");

                    b.Property<string>("ProviderDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("NM_EXIBICAO_PROVEDOR");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_USUARIO_LOGIN_ID_USUARIO");

                    b.ToTable("T_USUARIO_LOGIN", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("ID_USUARIO");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("ID_PERFIL");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_USUARIO_PERFIL_ID_PERFIL");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_USUARIO_PERFIL_ID_USUARIO");

                    b.ToTable("T_USUARIO_PERFIL", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("TX_PROVEDOR_LOGIN");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("NM_TOKEN");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("TX_VALOR_TOKEN");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("T_USUARIO_TOKEN", (string)null);
                });

            modelBuilder.Entity("FSP.Api.Domain.Entities.Post.Post", b =>
                {
                    b.HasOne("FSP.Api.Domain.Entities.Usuario.ApplicationUser", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("FSP.Api.Domain.Entities.Usuario.Perfil", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("FSP.Api.Domain.Entities.Usuario.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("FSP.Api.Domain.Entities.Usuario.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("FSP.Api.Domain.Entities.Usuario.Perfil", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FSP.Api.Domain.Entities.Usuario.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("FSP.Api.Domain.Entities.Usuario.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
